# This file has been autogenerated. Do not change by hand.

#' Create a parameter object for the function createEvaluationCohort
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param xSpecCohortId                    The number of the "extremely specific (xSpec)"
#'                                         cohortdefinition id in the cohort table (for noisy
#'                                         positives).
#' @param xSensCohortId                    The number of the "extremely sensitive (xSens)"
#'                                         cohortdefinition id in the cohort table (for noisy
#'                                         negatives).
#' @param prevalenceCohortId               The number of the cohort definition id to determine
#'                                         the disease prevalence.
#' @param xSpecCohortSize                  The recommended xSpec sample size to use in model (default = 5000)
#' @param covariateSettings                A covariateSettings object as generated
#'                                         using createCovariateSettings().
#' @param modelPopulationCohortId           The number of the cohort to be used as a base population for
#'                                         the model. If set to 0, the entire database population will be
#'                                         used.
#' @param modelPopulationCohortIdStartDay   The number of days relative to the mainPopulationCohortId
#'                                         cohort start date to begin including visits.
#' @param modelPopulationCohortIdEndDay     The number of days relative to the mainPopulationCohortId
#'                                         cohort start date to end including visits.
#' @param evaluationPopulationCohortId           The number of the cohort to be used as a base population for
#'                                         the evalution cohort. If set to 0, the entire database population will be
#'                                         used.
#' @param evaluationPopulationCohortIdStartDay   The number of days relative to the evaluationPopulationCohortId
#'                                         cohort start date to begin including visits.
#' @param evaluationPopulationCohortIdEndDay     The number of days relative to the evaluationPopulationCohortId
#'                                         cohort start date to end including visits.
#' @param baseSampleSize                   The maximum number of subjects in the evaluation cohort.
#' @param lowerAgeLimit                    The lower age for subjects in the model.
#' @param upperAgeLimit                    The upper age for subjects in the model.
#' @param visitLength                      The minimum length of index visit for acute outcomes.
#' @param visitType                        The concept_id for the visit type.
#' @param gender                           The gender(s) to be included.
#' @param race                             The race(s) to be included.
#' @param ethnicity                        The ethnicity(s) to be included.
#' @param startDate                        The starting date for including subjects in the model.
#' @param endDate                          The ending date for including subjects in the model.
#' @param modelId                          A string used to generate the file names for this model.
#' @param evaluationCohortId               A string used to generate the file names for this evaluation cohort.
#' @param excludeModelFromEvaluation       Should subjects used in the model be excluded from the
#'                                         evaluation cohort?
#' @param removeSubjectsWithFutureDates    For buggy data with data in the future: ignore subjects
#'                                         with dates in the future?
#' @param saveEvaluationCohortPlpData      Should the large PLP file for the evaluation cohort be
#'                                         saved? To be used for debugging purposes.
#' @param modelType                        The type of health outcome in the model either "acute"
#'                                         or"chronic".
#'
#' @export
createCreateEvaluationCohortArgs <- function(xSpecCohortId,
                                             xSensCohortId,
                                             prevalenceCohortId,
                                             xSpecCohortSize = 5000,
                                             covariateSettings = createDefaultChronicCovariateSettings(excludedCovariateConceptIds = c(),
                                                                                                       addDescendantsToExclude = TRUE),
                                             modelPopulationCohortId = 0,
                                             modelPopulationCohortIdStartDay = 0,
                                             modelPopulationCohortIdEndDay = 0,
                                             evaluationPopulationCohortId = 0,
                                             evaluationPopulationCohortIdStartDay = 0,
                                             evaluationPopulationCohortIdEndDay = 0,
                                             baseSampleSize = 2e+06,
                                             lowerAgeLimit = 0,
                                             upperAgeLimit = 120,
                                             visitLength = 0,
                                             visitType = c(9201,9202,9203,581477),
                                             gender = c(8507, 8532),
                                             race = 0,
                                             ethnicity = 0,
                                             startDate = "19001010",
                                             endDate = "21000101",
                                             modelId = "main",
                                             evaluationCohortId = "main",
                                             excludeModelFromEvaluation = FALSE,
                                             removeSubjectsWithFutureDates = TRUE,
                                             saveEvaluationCohortPlpData = FALSE,
                                             modelType = "acute") {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createCreateEvaluationCohortArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}

#' Create a parameter object for the function testPhenotypeAlgorithm
#'
#' @details
#' Create an object defining the parameter values.
#'
#' @param cutPoints           A list of threshold predictions for the evaluations.  Include "EV"for the
#'                            expected value
#' @param phenotypeCohortId   The ID of the cohort to evaluate in the specified cohort table.
#' @param washoutPeriod       The mininum required continuous observation time prior to indexdate for
#'                            subjects within the cohort to test (Default = 0).
#' @param splayPrior          The number of days to allow for test phenotype visit date prior to evaluation date
#' @param splayPost           The number of days to allow for test phenotype visit date after evaluation date
#'
#' @export
createTestPhenotypeAlgorithmArgs <- function(cutPoints = c("EV"),
                                             phenotypeCohortId,
                                             washoutPeriod = 0,
                                             splayPrior = 7,
                                             splayPost = 7) {
  # First: get default values:
  analysis <- list()
  for (name in names(formals(createTestPhenotypeAlgorithmArgs))) {
    analysis[[name]] <- get(name)
  }
  # Second: overwrite defaults with actual values:
  values <- lapply(as.list(match.call())[-1], function(x) eval(x, envir = sys.frame(-3)))
  for (name in names(values)) {
    if (name %in% names(analysis))
      analysis[[name]] <- values[[name]]
  }
  class(analysis) <- "args"
  return(analysis)
}
