# Copyright 2022 Observational Health Data Sciences and Informatics
#
# This file is part of PheValuator
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
styler::style_pkg()
OhdsiRTools::checkUsagePackage("PheValuator")
OhdsiRTools::updateCopyrightYearFolder()
devtools::spell_check()

# Create manual and vignettes
shell("rm extras/PheValuator.pdf")
shell("R CMD Rd2pdf ./ --output=extras/PheValuator.pdf")

rmarkdown::render("vignettes/EvaluatingPhenotypeAlgorithms.rmd",
                  output_file = "../inst/doc/EvaluatingPhenotypeAlgorithms.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          toc_depth = 3,
                                          number_sections = TRUE))

pkgdown::build_site()
OhdsiRTools::fixHadesLogo()

# Create arg functions:
rCode <- c("# This file has been autogenerated. Do not change by hand. ")
rCode <- ParallelLogger::createArgFunction("createEvaluationCohort",
                                           excludeArgs = c("connectionDetails",
                                                           "cdmDatabaseSchema",
                                                           "oracleTempSchema",
                                                           "tempEmulationSchema",
                                                           "workDatabaseSchema",
                                                           "cohortDatabaseSchema",
                                                           "cohortTable",
                                                           "outFolder",
                                                           "evaluationCohortId",
                                                           "cdmVersion"),
                                           rCode = rCode)
rCode <- ParallelLogger::createArgFunction("testPhenotypeAlgorithm",
                                           excludeArgs = c("connectionDetails",
                                                           "cdmDatabaseSchema",
                                                           "cohortDatabaseSchema",
                                                           "cohortTable",
                                                           "outFolder",
                                                           "evaluationCohortId"),
                                           rCode = rCode)
writeLines(rCode, "R/CreateArgFunctions.R")
OhdsiRTools::formatRFile("R/CreateArgFunctions.R")


